import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Community Pixel Art", description: "A permanent community-owned pixel canvas for Torn City." };

const fallbackStyles = `
  :root { color-scheme: dark; } * { box-sizing: border-box; }
  body { margin: 0; min-height: 100vh; color: #d7dde0; font-family: Arial, Helvetica, sans-serif; background-color: #cbd0cd; background-image: linear-gradient(45deg, rgba(255,255,255,.23) 25%, transparent 25%), linear-gradient(-45deg, rgba(255,255,255,.18) 25%, transparent 25%), linear-gradient(45deg, transparent 75%, rgba(255,255,255,.18) 75%), linear-gradient(-45deg, transparent 75%, rgba(255,255,255,.22) 75%); background-size: 24px 24px; background-position: 0 0, 0 12px, 12px -12px, -12px 0; }
  button { font: inherit; } a { color: #ffb12a; } .app-shell { max-width: 1440px; margin: 0 auto; padding: 18px; }
  .app-header { display: flex; align-items: center; justify-content: space-between; gap: 18px; margin-bottom: 16px; padding: 14px 18px; border: 1px solid #080a0b; border-radius: 4px; background: linear-gradient(180deg, #303b40 0%, #111719 100%); box-shadow: 0 3px 0 #697173, 0 8px 20px rgba(0,0,0,.34); }
  .app-header p, .panel-kicker { margin: 0; color: #f4a11b; font: 700 10px/1.2 Arial, sans-serif; letter-spacing: .16em; } .app-header h1 { margin: 4px 0 0; color: #f0f2f1; font-size: 22px; letter-spacing: .06em; } .app-header > div:last-child { display: flex; align-items: center; gap: 14px; font-size: 13px; } .admin-link, .logout-button { color: #f4a11b; font-weight: bold; } .logout-button, .text-button { border: 0; padding: 0; background: none; cursor: pointer; }
  .canvas-layout { display: grid; grid-template-columns: minmax(0, 1fr) 330px; gap: 16px; } .panel { border: 1px solid #101415; border-radius: 4px; background: #1d2528; box-shadow: 0 2px 0 #697173, 0 6px 18px rgba(0,0,0,.27); overflow: hidden; } .canvas-panel { padding: 12px; } .canvas-toolbar { display: flex; justify-content: space-between; align-items: center; gap: 12px; margin: -12px -12px 12px; padding: 10px 12px; color: #cdd4d5; font-size: 12px; background: #111718; border-bottom: 1px solid #394347; }
  .zoom-controls { display: flex; align-items: center; gap: 7px; } .zoom-controls button { width: 25px; height: 23px; border: 1px solid #495357; border-radius: 2px; color: #fff; background: #293236; cursor: pointer; } .zoom-controls button:disabled { cursor: not-allowed; opacity: .42; }
  .canvas-viewport { overflow: auto; max-width: 100%; max-height: 72vh; border: 1px solid #111; background: #141a1c; } .canvas-viewport.is-zoomed { cursor: grab; } .canvas-viewport.is-zoomed:active { cursor: grabbing; } .canvas-grid { display: grid; min-width: 0; min-height: 0; background: #2b2f33; } .pixel-cell { display: block; min-width: 0; min-height: 0; margin: 0; padding: 0; border: .5px solid #171b1d; cursor: crosshair; } .pixel-cell:hover { outline: 2px solid #ffae24; outline-offset: -2px; z-index: 2; } .pixel-cell.is-selected { outline: 2px solid #fff; outline-offset: -2px; box-shadow: inset 0 0 0 2px #ef9f19; z-index: 1; } .canvas-help { margin: 10px 2px 0; color: #9aa6a9; font-size: 11px; }
  aside { display: grid; align-content: start; gap: 16px; } .purchase-panel, .leaderboard { padding: 16px; } .panel h2 { margin: 5px 0 14px; color: #f1f2ee; font-size: 18px; } .selection-summary { display: flex; align-items: baseline; gap: 8px; padding: 10px; border: 1px solid #3c474a; background: #131a1c; } .selection-summary b { color: #f7af29; font-size: 24px; } .selection-summary span, .muted { color: #94a0a3; font-size: 12px; } .coordinate-list { min-height: 36px; margin: 10px 0; color: #c5ced0; font: 11px/1.5 ui-monospace, monospace; } .color-picker { display: flex; align-items: center; justify-content: space-between; gap: 10px; padding: 10px 0; border-top: 1px solid #3a4447; border-bottom: 1px solid #3a4447; color: #b7c0c2; font-size: 12px; } .color-picker > div { display: flex; flex-wrap: wrap; justify-content: flex-end; gap: 5px; } .color-option { width: 20px; height: 20px; border: 2px solid #526064; border-radius: 2px; cursor: pointer; } .color-option.active { outline: 2px solid #f6aa22; outline-offset: 1px; } .price-line { margin: 14px 0 10px; color: #b5bec0; font-size: 12px; } .price-line b { color: #f2aa29; }
  .button { width: 100%; border: 1px solid #9e5c10; border-radius: 2px; padding: 11px 14px; color: #fff5dc; font-weight: bold; letter-spacing: .035em; background: linear-gradient(180deg, #e08717, #a34c0e); box-shadow: inset 0 1px rgba(255,255,255,.3); cursor: pointer; } .button:hover { filter: brightness(1.13); } .button:disabled { cursor: not-allowed; opacity: .42; } .text-button { display: block; width: 100%; margin-top: 11px; color: #aeb9bb; font-size: 12px; text-decoration: underline; } .notice { margin: 10px 0 0; color: #ffcf75; font-size: 12px; }
  .leaderboard ol { margin: 0; padding: 0; list-style: none; } .leaderboard li { display: flex; justify-content: space-between; padding: 9px 0; border-bottom: 1px solid #354044; color: #c8d0d1; font-size: 13px; } .leaderboard li strong { color: #f7ad24; } .leaderboard .muted { margin: 13px 0 0; }
  .landing { display: grid; grid-template-columns: 1fr minmax(320px, 400px); align-items: center; gap: 64px; min-height: 100vh; max-width: 1100px; padding: 26px; } .landing-kicker { color: #75480a; font-size: 11px; font-weight: 800; letter-spacing: .16em; } .landing h1 { margin: 10px 0; color: #20292c; font-size: clamp(44px, 8vw, 86px); line-height: .9; letter-spacing: -.05em; text-shadow: 2px 2px rgba(255,255,255,.5); } .landing-copy { max-width: 400px; color: #445053; font-size: 17px; line-height: 1.5; } .login-panel { padding: 22px; border: 1px solid #101415; border-radius: 4px; background: #1d2528; box-shadow: 0 2px 0 #697173, 0 10px 30px rgba(0,0,0,.3); } .login-panel h2 { margin: 6px 0; color: white; } .login-panel > input { display: block; width: 100%; margin: 16px 0 10px; border: 1px solid #465256; border-radius: 2px; padding: 12px; color: white; background: #111719; } .login-panel .button { margin-top: 3px; } .api-notice { margin-top: 18px; padding-top: 14px; border-top: 1px solid #3a4447; color: #aeb8ba; font-size: 11px; } .api-notice dl { display: grid; grid-template-columns: 1fr 1fr; gap: 7px 10px; margin: 10px 0 0; } .api-notice dt { color: #7f8e91; } .api-notice dd { margin: 0; color: #c7d0d1; }
  .payment-overlay { position: fixed; inset: 0; z-index: 20; display: grid; place-items: center; padding: 18px; background: rgba(4,7,8,.76); } .payment-modal { position: relative; width: min(440px, 100%); padding: 24px; border: 1px solid #535e60; border-radius: 4px; background: #182023; box-shadow: 0 18px 60px rgba(0,0,0,.7); } .payment-modal h2 { margin: 5px 0 18px; color: white; } .modal-close { position: absolute; top: 10px; right: 12px; border: 0; color: #aab4b6; background: none; font-size: 26px; cursor: pointer; } .payment-rule { padding: 12px; border-left: 4px solid #efa625; background: #111719; color: #ffc457; } .payment-modal p { color: #bdc6c8; line-height: 1.5; font-size: 13px; } .payment-modal dl { display: grid; grid-template-columns: 92px 1fr; gap: 8px; margin: 16px 0; padding: 13px; background: #111719; font-size: 13px; } .payment-modal dt { color: #96a2a5; } .payment-modal dd { margin: 0; color: #f3f5f1; font-weight: bold; } .payment-modal code { color: #f9b234; } .payment-note { font-size: 12px !important; }
  .admin-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; } .admin-stat { padding: 16px; } .admin-stat p { margin: 0; color: #aeb9bb; font-size: 12px; } .admin-stat strong { display: block; margin-top: 8px; color: #f7ad24; font-size: 34px; } .admin-note { margin-top: 16px; padding: 18px; } .admin-note p { color: #bdc6c8; } 
  @media (max-width: 960px) { .canvas-layout, .landing { grid-template-columns: 1fr; } .admin-grid { grid-template-columns: repeat(2, 1fr); } .canvas-viewport { max-height: 62vh; } .landing { gap: 18px; min-height: auto; padding-top: 90px; } } @media (max-width: 580px) { .app-shell { padding: 9px; } .app-header { align-items: flex-start; flex-direction: column; } .app-header > div:last-child { width: 100%; justify-content: space-between; } .canvas-toolbar { align-items: flex-start; flex-direction: column; } .admin-grid { grid-template-columns: 1fr; } }
`;

export default function RootLayout({ children }: { children: React.ReactNode }) { return <html lang="en"><head><style>{fallbackStyles}</style></head><body>{children}</body></html>; }
